image: bnewbold/fatcat-test-base:latest

stages:
  - test

before_script:
   - pip install --upgrade pip
   - pip install pytest

tests:
  stage: test
  script:
    - python setup.py develop
    - pytest

