image: tirtir/fuzzycat-ci:latest

stages:
  - test

before_script:
   - pip3 install --upgrade pip
   - pip3 install pytest

tests:
  stage: test
  script:
    - python3 --version
    - pipenv install
    - pipenv run pytest

