# https://hub.docker.com/r/tirtir/fuzzycat-ci/tags
# https://git.sr.ht/~miku/dockerfiles/blob/master/fuzzycat-ci/Dockerfile
image: tirtir/fuzzycat-ci:latest

stages:
  - test

before_script:
   - pip3 install --upgrade pip

tests:
  stage: test
  script:
    - python3 --version
    - make deps
    - make test
